name=SoftwareSerial
version=1.0.0
author= Arduino
maintainer=
sentence=SoftwareSerial library for the MFL Arduino Core.
paragraph=Adapted from the Arduino SoftwareSerial library.
category=Communication
url=
architectures=gd32